package org.opendaylight.iotdm.constant.enumeration;

import java.math.BigInteger;

/**
 * Created by wenxshi on 3/31/15.
 */
public enum ExecResultType  implements EnumApi {
    STATUS_REQUEST_UNSUPPORTED("STATUS_REQUEST_UNSUPPORTED", BigInteger.valueOf(1)),
    STATUS_REQUEST_DENIED("STATUS_REQUEST DENIED", BigInteger.valueOf(2)),
    STATUS_CANCELLATION_DENIED("STATUS_CANCELLATION_DENIED", BigInteger.valueOf(3)),
    STATUS_INTERNAL_ERROR("STATUS_INTERNAL_ERROR", BigInteger.valueOf(4)),
    STATUS_INVALID_ARGUMENTS("STATUS_INVALID_ARGUMENTS", BigInteger.valueOf(5)),
    STATUS_RESOURCES_EXCEEDED("STATUS_RESOURCES_EXCEEDED", BigInteger.valueOf(6)),
    STATUS_FILE_TRANSFER_FAILED("STATUS_FILE_TRANSFER_FAILED", BigInteger.valueOf(7)),
    STATUS_FILE_TRANSFER_SERVER_AUTHENTICATION_FAILURE("STATUS_FILE_TRANSFER_SERVER_AUTHENTICATION_FAILURE", BigInteger.valueOf(8)),
    STATUS_UNSUPPORTED_PROTOCOL("STATUS_UNSUPPORTED_PROTOCOL", BigInteger.valueOf(9)),
    STATUS_UPLOAD_FAILED("STATUS_UPLOAD_FAILED", BigInteger.valueOf(10)),
    STATUS_FILE_TRANSFER_FAILED_MULTICAST_GROUP_UNABLE_JOIN("STATUS_FILE_TRANSFER_FAILED_MULTICAST_GROUP_UNABLE_JOIN", BigInteger.valueOf(11)),
    STATUS_FILE_TRANSFER_FAILED_SERVER_CONTACT_FAILED("STATUS_FILE_TRANSFER_FAILED_SERVER_CONTACT_FAILED", BigInteger.valueOf(12)),
    STATUS_FILE_TRANSFER_FAILED_FILE_ACCESS_FAILED("STATUS_FILE_TRANSFER_FAILED_FIL`E_ACCESS_FAILED", BigInteger.valueOf(13)),
    STATUS_FILE_TRANSFER_FAILED_DOWNLOAD_INCOMPLETE("STATUS_FILE_TRANSFER_FAILED_DOWNLOAD_INCOMPLETE", BigInteger.valueOf(14)),
    STATUS_FILE_TRANSFER_FAILED_FILE_CORRUPTED("STATUS_FILE_TRANSFER_FAILED_FILE_CORRUPTED", BigInteger.valueOf(15)),
    STATUS_FILE_TRANSFER_FILE_AUTHENTICATION_FAILURE("STATUS_FILE_TRANSFER_FILE_AUTHENTICATION_FAILURE", BigInteger.valueOf(16)),
    //todo duplicated with 8,9
//    STATUS_FILE_TRANSFER_FAILED("STATUS_FILE_TRANSFER_FAILED", BigInteger.valueOf(17)),
//    STATUS_FILE_TRANSFER_SERVER_AUTHENTICATION_FAILURE("STATUS_FILE_TRANSFER_SERVER_AUTHENTICATION_FAILURE", BigInteger.valueOf(18)),
    STATUS_FILE_TRANSFER_WINDOW_EXCEEDED("STATUS_FILE_TRANSFER_WINDOW_EXCEEDED", BigInteger.valueOf(19)),
    STATUS_INVALID_UUID_FORMAT("STATUS_INVALID_UUID_FORMAT", BigInteger.valueOf(20)),
    STATUS_UNKNOWN_EXECUTION_ENVIRONMENT("STATUS_UNKNOWN_EXECUTION_ENVIRONMENT", BigInteger.valueOf(21)),
    STATUS_DISABLED_EXECUTION_ENVIRONMENT("STATUS_DISABLED_EXECUTION_ENVIRONMENT", BigInteger.valueOf(22)),
    STATUS_EXECUTION_ENVIRONMENT_MISMATCH("STATUS_EXECUTION_ENVIRONMENT_MISMATCH", BigInteger.valueOf(23)),
    STATUS_DUPLICATE_DEPLOYMENT_UNIT("STATUS_DUPLICATE_DEPLOYMENT_UNIT", BigInteger.valueOf(24)),
    STATUS_SYSTEM_RESOURCES_EXCEEDED("STATUS_SYSTEM_RESOURCES_EXCEEDED", BigInteger.valueOf(25)),
    STATUS_UNKNOWN_DEPLOYMENT_UNIT("STATUS_UNKNOWN_DEPLOYMENT_UNIT", BigInteger.valueOf(26)),
    STATUS_INVALID_DEPLOYMENT_UNIT_STATE("STATUS_INVALID_DEPLOYMENT_UNIT_STATE", BigInteger.valueOf(27)),
    STATUS_INVALID_DEPLOYMENT_UNIT_UPDATE_DOWNGRADE_DISALLOWED("STATUS_INVALID_DEPLOYMENT_UNIT_UPDATE_DOWNGRADE_DISALLOWED", BigInteger.valueOf(28)),
    STATUS_INVALID_DEPLOYMENT_UNIT_UPDATE_UPGRADE_DISALLOWED("STATUS_INVALID_DEPLOYMENT_UNIT_UPDATE_UPGRADE_DISALLOWED", BigInteger.valueOf(29)),
    STATUS_INVALID_DEPLOYMENT_UNIT_UPDATE_VERSION_EXISTS("STATUS_INVALID_DEPLOYMENT_UNIT_UPDATE_VERSION_EXISTS", BigInteger.valueOf(30));


    private String interpretation;
    private BigInteger value;

    ExecResultType(String interpretation, BigInteger value) {
        this.interpretation = interpretation;
        this.value = value;
    }

    public String getInterpretation() {
        return interpretation;
    }

    public BigInteger getValue() {
        return value;
    }
}